# BTEX

---
execute:
  echo: false
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
---

From the 2016 report:

Benzene, toluene, ethylbenzene, m,p-xylene, and o-xylene are the aromatic hydrocarbons that are commonly referred to as BTEX. Volcanoes and forest fires are natural sources of benzene, and benzene is also a component in cigarette smoke, crude oil, and gasoline (ATSDR, 2005a). Benzene breaks down slowly in water and soil, but concentrations do not build up in plants and animals (ATSDR, 2005a). A natural part of crude oil, toluene is used to produce gasoline, paint, paint thinner, lacquer, and adhesives (ATSDR, 2001). Toluene can enter surface water due to petroleum or solvent spills and engine exhaust, but does not buildup to high concentrations in animals (ATSDR, 2001). Ethylbenzene is a colorless liquid found naturally in coal tar and petroleum, and is often used as a solvent and as a component in fuel, ink, insecticide, and paint (ATSDR, 1999). Xylene has three forms or isomers called meta-xylene, para-xylene, and ortho-xylene, which are reported in this study as m,p-xylene and o-xylene. As a natural part of petroleum and coal tar, xylene has many uses as a solvent, cleaner, paint thinner, and a small component of gasoline (ATSDR, 2005b). Once xylene enters surface water, it evaporates quickly into the air, but a small amount can concentrate in aquatic life (ATSDR, 2005b). The ADEC standard is 10 µg/L for total aromatic hydrocarbons in freshwater for the growth and propagation of fish, shellfish, other aquatic life, and wildlife (see Appendix 2) (ADEC, 2012). Additionally, the ADEC requires that surface waters do not have any floating oil, film, sheen, or discoloration due to hydrocarbons and that in shoreline or bottom sediments, there cannot be any concentration of petroleum hydrocarbons that cause deleterious effects to aquatic life (ADEC, 2012).

The highest level of BTEX in the mainstem occurred at Mile 1.5 at a level of 15.2 µg/L in summer 2002, and the lowest levels were reported as non-detect because they were below the MDLs and MRLs. No BTEX was reported in any of the spring samples, but high levels were detected in the lower river during the summer (Table 25). No median of BTEX exceeded the Alaska standard, but individual samples from Mile 1.5 and 6.5 exceeded the standard during the summer of 2000, 2001, 2002 and 2003. A clear upward trend is evident from Mile 23 to Mile 1.5, and Mile 40 and Mile 43 show BTEX medians above the next two downstream sites. No BTEX was ever detected at Mile 70 (Figures 114 &115).

In the tributaries, concentrations ranged from 6.65 µg/L in the Moose River in summer 2002 to non-detects reported in many instances. None of the tributaries had reported levels above the standard (Table 51). However, Beaver Creek, Soldotna Creek, the Moose River, the Killey River each had multiple instances of detection, and the Russian River reported one occasion of detection in summer 2008 (Figures 116 &117).
 
A trend analysis was conducted using the average and median values for data collected during the summer 2000-2013. The concentrations of BTEX throughout the entire Kenai River show higher levels of BTEX in the lower part of the Kenai River and very low concentrations in the headwaters (Figure 114 and Figure 115). The same analysis was done for each sampling station at the Kenai River; all but three stations show a decrease in BTEX concentration over time. Station at Mile 10.1 shows a decreasing trend until 2010. A Sampling event in 2012 starts an upward trend in the BTEX concentration (Figures 118-125).

All of the aromatic hydrocarbons of BTEX are typically associated with gasoline (Oasis Environmental, Inc., 2004). Litchfield and Kyle suggest that motorized boats could be the primary contamination source since peak times of outboard motor use coincided with peak concentrations of BTEX (1992). In 2003, the Kenai Watershed Forum determined that the majority of hydrocarbon contamination resulted from unburned refined gasoline product with outboard motors as the most likely source. In March 2008, the Alaska Department of Natural Resources Division of Parks and Recreation banned the use of two-stroke engines, with the exception of direct fuel injected (DFI) engines, within the Kenai River Special Management Area.




```{r echo = F, warning=FALSE, message=FALSE,fig.height=8, fig.width=10}

# set parameter
characteristic <- "Benzene, toluene, ethyl benzene, xylenes mix"

# source static regulatory criteria boxplot function
source("functions/static_boxplot_function.R")

# source table download function
source("functions/table_download.R")
download_tbl(char = characteristic)

```
