# Introduction

This report summarizes water quality data collected between summer 2000 and summer 2022 from 22 sampling locations in the Kenai River mainstem and its tributaries. Local, state, federal, and tribal government entities, as well as several local area non‐profits formed a cooperative partnership so that sampling teams from various agencies were able to collect water samples twice per year, once in the spring and once in the summer, and this effort continues beyond the publication of this report. The locations of the sampling sites are identified with maps, GPS coordinates, and photographs. Trends in the data are highlighted, and the results are compared to the Alaska and federal water quality standards for freshwater aquatic life.

The water quality data focuses on metals, nutrients, hydrocarbons, fecal coliform bacteria, and various field parameters. Arsenic, cadmium, chromium, copper, lead, and zinc are the dissolved metals that have been analyzed, and calcium, iron, and magnesium were reported as total metals. Additionally, the report focuses on the nutrients nitrate and phosphorus. Specifically, the hydrocarbons that were collected and analyzed include diesel range organics, gasoline range organics, residual range organics, benzene, toluene, ethylbenzene, m,p-xylene, and o-xylene. Fecal coliform bacteria, pH, specific conductance, total suspended solids, turbidity, and water temperature are the remaining parameters that have been included in the analysis.

The results are displayed in graphs with associated written analyses and tables. The graphs display the median and variance for each parameter at a specific location, and these graphs are separated depending on whether the data was collected in the spring or in the summer. In some cases, parameters were present in levels that could not be detected by current laboratory analysis, and when this occurred with over 80% of the samples, scatter plots have been displayed omitting the unknown low levels.

\[previous reports published in 2007 and 2016\]

\[Text from 2016 report: A trend analysis was conducted for the following parameters: Lead, Zinc and BTEX; based on the nature of the data, a polynomial line was used because it is the best way to capture and represent the fluctuations in the data.\]

Complete data tables can be found in Appendix XXX and XXX, which are organized by parameter and site location, respectively.

\newpage
