# Turbidity 

---
execute:
  echo: false
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
---

Turbidity measures the degree to which suspended and dissolved materials cause light to scatter instead of being transmitted in straight lines, and these materials consist of silt, clay, chemicals, microscopic organisms, and fine organic or inorganic matter (Bash and others, 2001). Turbidity varies naturally; higher turbidities are typically found in watersheds fed by glacial melt water, and turbidity generally increases from headwater tributaries to mainstems and estuaries (Bash and others, 2001). Even though salmonids can naturally live in turbid water systems, they do not always cope well with increases in suspended sediments, and these high levels in suspended sediments can cause fatalities, while lower levels can result in difficulty finding food, reduced growth, increased stress, and difficulty migrating (Bash and others, 2001). The ADEC standard states that turbidity may not exceed 25 NTU above natural conditions in freshwater or 5 NTU above natural conditions in lakes for the growth and propagation of fish, shellfish, other aquatic life, and wildlife (see Appendix X) (ADEC, 2012).

The highest level of turbidity occurred at Mile 6.5 in spring 2006 and was detected at 3200 NTU, and the lowest level in the mainstem was 1 NTU at Mile 70 in spring 2009 (Table 30). The highest medians and degree of variance for turbidity were in the estuary for both the spring and the summer, and the lowest median occurred at Mile 50. In the summer, from Mile 43 to Mile 1.5, the median level of turbidity generally increased. The spring medians in the estuary and Upper River were higher than the summer medians, but the rest of the mainstem had higher medians in the summer (Figure X).

In the tributaries, the highest level of turbidity was 336 NTU at Beaver Creek in spring 2010, and the lowest level was at Russian River with the level of 0.02 NTU from summer 2006 (Table X). During the summer, the Killey River had the highest median at 41 NTU, while the other tributaries all had medians less than 20 NTU. In the spring, Beaver Creek had the highest median, followed by No Name Creek and then Funny River. Russian River had the lowest turbidity median in both the summer and the spring. Killey River exhibited the largest seasonal difference in medians by increasing around 35 NTU from the spring to the summer. In contrast, Beaver Creek decreased approximately 13.3 NTU during the summer. The tributaries did not display a clear seasonal trend for increased or decreased turbidity (Figure X).


```{r echo = F, warning=FALSE, message=FALSE,fig.height=10}

# set parameter
parameter <- "Turbidity"

# source static regulatory criteria boxplot function
source("functions/static_boxplot_function.R")
make_boxplot(param = parameter)

# source calculated regulatory criteria plot(s) function


# source table download function
source("functions/table_download.R")
download_tbl(param = parameter)

```
