# Methods

We collected water samples at 13 locations along the Kenai River mainstem and from eight tributaries near their confluence points (see @fig-map2). These locations were selected by a technical working group in 1997 to represent diverse regions through the Kenai River watershed's ambient water quality conditions. Sampling occurred in the spring and the summer each year beginning in summer 2000.

After a half‐day training session in the week prior, staff from governmental and non‐governmental agencies dispersed between 7:00 AM - 9:00 AM to sampling locations in teams of two or more to collect samples. All samples were collected on the same day, and the timing of the sampling coincided with an outgoing tide, near low tide, to reduce the potential of collecting saline water from Cook Inlet (see Appendix X for timing). Typically, the individual collecting the sample waded into the water until the water level was around two feet deep, and the sample was collected while facing upstream. If the individual collected the sample using a boat, the samples were collected from the bow while the boat faced upstream. The bottles were placed approximately one foot below the surface to collect the water samples and then preserved in a cooler for transportation to the laboratory. Beginning in spring 2002, two duplicate samples were collected for quality control. These procedures follow the protocols established in a Quality Assurance Project Plan (QAPP) that was originally approved by the ADEC in 2001 and later revised and approved by ADEC again in 2013, 2019, 2020. The QAPP was also reviewed and approved by the Region 10 Environmental Protection Agency office in 2023. The QAPP is available from Kenai Watershed Forum's website[^methods-1].

[^methods-1]: https://www.kenaiwatershed.org/science-in-action/research-information/water-quality/

We used the R programming language in Posit software for all analyses in this report, and generated this report using the Quarto publishing framework. It is hosted through Kenai Watershed Forum's GitHub account. The report is available both as an online report here and is also downloadable in PDF form \[when draft is complete\].

In instances where data was reported as not detected the half of the method detection limit (MDL) or method reporting limit (MRL) was used to estimate the values and run the analysis. The MRL was used because during the early years of the project, the lab only provided this information and not the MDL.

\newpage
